### ISSUE TITLE
这个文件没上传

### ISSUE THREAD

**Issue by jacin1** [foolstack-omg/block-tech-sharing#4]
require('@initia/initia.js');

**Comment by forusforyou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wytiger** [comment]
同求

**Comment by forusforyou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
