### ISSUE TITLE
https://faucet-api.initiation-1.initia.xyz/claim 400

### ISSUE THREAD

**Issue by udbyygyt** [foolstack-omg/block-tech-sharing#5]
最后一步claim报400了，有人遇到吗
error Error: Request failed with status code 400

**Comment by Openegg15** [comment]
This is a follow-up to [#1822](https://rausauboocad.net/4/7446717) and [#100 ](https://tremblesyringeillusive.com/ne8muthq4i?key=474c9752b6833707c410d6e7be2d821f)

**Comment by laike** [comment]
我也遇到了 不知道怎么办

**Comment by wytiger** [comment]
你们前面没问题吗？
